<?php

namespace App\Swoole;

use Hyperf\Framework\Bootstrap\WorkerExitCallback;
use Swoole\Server as SwooleServer;

class WorkerExit extends WorkerExitCallback
{
    public function onWorkerExit(SwooleServer $server, int $workerId)
    {
        parent::onWorkerExit($server, $workerId); // TODO: Change the autogenerated stub
        if ($workerId == 0) {
            swoole_timer_clear_all();
        }
    }

}