<?php

namespace App\Swoole;

use App\Controller\WebSocket\RoomRedisManager;
use Hyperf\Framework\Bootstrap\WorkerStartCallback;
use Swoole\Server as SwooleServer;

class WorkerStart extends WorkerStartCallback
{
    public function onWorkerStart(SwooleServer $server, int $workerId)
    {
        parent::onWorkerStart($server, $workerId); // TODO: Change the autogenerated stub
        if ($workerId == 0) {
            swoole_timer_tick(1000 * 15, function () {
                RoomRedisManager::clearnNotActivityFd();
            });
        }
    }
}